### ISSUE TITLE
great idea! -  but get error message when clicking Addin (as in GIF example image)

### ISSUE THREAD

**Issue by sfd99** [milosvil/caretTuneGrid#1]
Great idea, Milos!.

I Installed the addin f/ GitHub:
    install_github("milosvil/caretTuneGrid")
Install went fine.

After loading
the **caret** and **caretTuneGrid** pkgs,
I typed in the Rstudio source panel
(and saved as an .R file) :

   fit <- train(mpg~. , data=mtcars,
             method="gbm")

I highlighted:     
       **gbm**
(just like in your example GIF),
and clicked on the Addin entry **Insert Tunegrid**,
but get this error message:

**Rstudio popup:** 
     "R code execution error"
_plus_
 **in Rstudio Console:**
    Error in gzfile(file, "rb") : cannot open the connection
    In addition: Warning message:
    In gzfile(file, "rb") :
    cannot open compressed file 'inst/tune_param_data.RDS',
   probable reason 'No such file or directory'
> 

It must be something silly on my part...
Heeelp  Milos!!.
 -- Any stepXstep instructions appreciated...

**SFd99
 latest version Rstudio and R
 Ubuntu Linux 14.04 LTS 32-bits**

**Comment by milosvil** [comment]
Hi. 
My mistake.
Please try now.
Thanks, Milos

**Comment by sfd99** [comment]
OK Milos -
 - works perfect now (after your fix).
_Thanks!  / Хвала вам!_

**SFd99
San Francisco**
